### ISSUE TITLE
Documenting OpenSSL::HMAC

### ISSUE THREAD

**Issue by reprah** [documenting-ruby/ruby#13]
I'd like to add code examples to the documentation for [OpenSSL::HMAC](http://ruby-doc.org/stdlib-2.0/libdoc/openssl/rdoc/OpenSSL/HMAC.html). I had to use it recently and want to help make its usage more obvious. Is this up for grabs?

**Comment by zzak** [comment]
Totally, let me know if you have any questions! Thank you for working on this!

**Comment by zzak** [comment]
@reprah Do you have any questions on this? You can also reach me via my email (listed on my github account), if that makes you more comfortable.

**Comment by reprah** [comment]
Not sure what you mean, did you think I was still working on this? I remember writing the documentation two months ago and [you committed it](https://github.com/documenting-ruby/ruby/pull/14). It's safe to close the issue!

**Comment by zzak** [comment]
@reprah oops, i must have missed the connection. thanks for pointing that out!
