### ISSUE TITLE
Documenting OptionParser

### ISSUE THREAD

**Issue by joelmccracken** [documenting-ruby/ruby#15]
I always wished the documentation was better here.

**Comment by zzak** [comment]
I have a few ideas, what are you thinking?

What could be improved or where have you had trouble in the past?

**Comment by joelmccracken** [comment]
I would like to see some isolated, simple examples instead of a singe complete example. I don't have any specific ideas right now.

**Comment by joelmccracken** [comment]
What are your thoughts?

**Comment by zzak** [comment]
a "don fong" made the following comment 6 days ago:

> suggestion: the "complete example" is a bit hard to read because it requires horizontal scrolling to see the whole line, yet because of the vertical length of the example, the horizontal scrollbar at the bottom may not be easily accessible. it might help to use a vertical scrollbar, to make the whole window (incl the horizontal scrollbar) fit on one screenful. or fold the code lines so that horizontal scrolling isn't necessary.

http://www.ruby-doc.org/stdlib-2.0.0/libdoc/optparse/rdoc/OptionParser.html

**Comment by zzak** [comment]
I'd like to refactor the complete example into smaller, well explained chunks. But I need to ask nobu first.

**Comment by joelmccracken** [comment]
That sounds good. It seems like some example command line usage/output
would make sense here.

**Comment by joelmccracken** [comment]
Have you asked Nobu about this yet, or gotten any feedback from him? I just started working on clarifying the documentation.

**Comment by joelmccracken** [comment]
Should I wait before I do any more work on this? I don't want to work on something that wouldn't be accepted. There are other areas to document =)

**Comment by zzak** [comment]
sorry for the delay, i will get back to you as soon as i get ahold of nobu

**Comment by joelmccracken** [comment]
no problem at all =)

**Comment by zzak** [comment]
@joelmccracken I have contacted nobu about this, if we don't hear back in a few days I will open a ticket for him on redmine.

Thanks!

**Comment by joelmccracken** [comment]
Hopefully later tonight i'll create a quick PR to show you what work i've already done. Thanks for helping me!

**Comment by joelmccracken** [comment]
PR with info at #19

**Comment by zzak** [comment]
@joelmccracken Sorry I haven't gotten back to you, here's a patch I started working on a while back but never got around to cleaning up. Maybe you can use it with your other patch?

``` diff
Index: lib/optparse.rb
===================================================================
--- lib/optparse.rb (revision 44927)
+++ lib/optparse.rb (working copy)
@@ -82,6 +82,33 @@
 #   p options
 #   p ARGV
 #
+# === Generating Help
+#
+# +optparse+ can be used to automatically generate help for the
+# commands you write:
+#
+#   require 'optparse'
+#   require 'open
+#
+#   # set the default name we
+#   name = 'world'
+#
+#   options = OptionParser.new do |opts|
+#     opts.banner = "Usage: example.rb [options]"
+#
+#     opts.on("-nNAME", "--name=NAME", "Name to say hello to (other than world)") do |n|
+#       name = n
+#     end
+#
+#     opts.on("-h", "--help", "Prints this help") do
+#       puts opts
+#       exit
+#     end
+#   end.parse!
+#
+#   puts "Hello #{name}"
+#
+#
 # === Complete example
 #
 # The following example is a complete Ruby program.  You can run it and see the
```

**Comment by joelmccracken** [comment]
I believe I have already integrated your suggestions into #19. Do you agree?

**Comment by zzak** [comment]
Gonna close this since we have an patch we're actively working on.
