### ISSUE TITLE
i am new to the ruby

### ISSUE THREAD

**Issue by nazarit** [documenting-ruby/ruby#17]
what are the diffrence between fetch,at,slice and index metods in ruby? pleae anyone explain me with example.
and also help me to strong in the ruby on rails.

**Comment by zzak** [comment]
@nazarit These methods are implemented on several classes of Ruby. Do you have a specific one you are having trouble with?

You can search for the docs on [ruby-doc.org](http://ruby-doc.com/search.html?cx=011815814100681837392%3Awnccv6st5qk&q=fetch&sa=Search&cof=FORID%3A9) for example.

Let me know if you have any other questions!

**Comment by zzak** [comment]
Sorry, without any feedback I must close this ticket.

If you have any further questions please contact me, my email is also listed under my github account: http://github.com/zzak
