### ISSUE TITLE
Documenting io/nonblock

### ISSUE THREAD

**Issue by reprah** [documenting-ruby/ruby#18]
[io/nonblock](http://ruby-doc.org/stdlib-2.1.0/libdoc/io/nonblock/rdoc/unknown.html) in the standard library looks undocumented so far. Looking at [nonblock.c](https://github.com/ruby/ruby/blob/trunk/ext/io/nonblock/nonblock.c) and playing with it in IRB shows it defines 3 methods on IO objects when it's required. Is this available for me to work on?

**Comment by zzak** [comment]
rdoc seems to be having trouble parsing these methods, i will have to look into it.

@reprah You're free to write the documentation for these methods and then we can figure out how to get rdoc to learn about them.

Thanks!

**Comment by reprah** [comment]
@zzak Hmm, I ran into an issue when writing usage examples for these methods. When I first saw the source code for them I expected them to work like [Python's facilities for setting nonblocking mode on a stream](http://docs.python.org/2/library/socket.html#socket.socket.setblocking), but in Ruby I can't seem to produce different results by setting nonblock mode on a socket/io object with this library. Like, it seems like a no-op. I tried to illustrate the problem [in this gist](https://gist.github.com/reprah/6843916).

I'm sure I'm just misunderstanding something. If you have time to offer your opinion I'd be very appreciative. Else I can just document the method names/args/return values so it's there for others to use.

Thank you :-)

**Comment by zzak** [comment]
You can also try checking the japanese docs here: http://doc.ruby-lang.org/ja/1.9.3/library/io=2fnonblock.html

And the tests for io/nonblock here: https://github.com/ruby/ruby/blob/trunk/test/io/nonblock/test_flush.rb

**Comment by reprah** [comment]
Thank you, that helps. I wanted to mention that the TestIONonblock test case still passed when I changed the stream's nonblock mode within the test from true to false, and it also passed when I commented out "require 'io/nonblock'" altogether (and any references to the methods there)! That's not supposed to happen, right?

**Comment by zzak** [comment]
Thanks @reprah!
