### ISSUE TITLE
Regexp#== contains incorrect examples

### ISSUE THREAD

**Issue by kyledecot** [documenting-ruby/ruby#20]
In both `1.9.3` and `2.0` documentation, the Regexp#== documentation contains invalid examples

http://www.ruby-doc.org/core-1.9.3/Regexp.html#method-i-3D-3D
http://www.ruby-doc.org/core-2.0/Regexp.html#method-i-3D-3D

```
/abc/  == /abc/   #=> false
/abc/  == /abc/   #=> false
/abc/  == /abc/   #=> false
/abc/ == /abc/   #=> false
```

The examples appear to be correct on github however 

https://github.com/documenting-ruby/ruby/blob/trunk/re.c#L2609

**Comment by zzak** [comment]
@kyledecot Thanks for the report! Unfortunately this is a bug in the third-party ruby-doc.org website, which we have no control over so I must close this ticket.

**Comment by ghost** [comment]
This looks to be a bug in rdoc.  Running  rdoc over the re.c file produces Darkfish output with the same missing character in the resulting HTML.

**Comment by zzak** [comment]
@Neurogami you're right, i can reproduce this with rdoc in trunk.

I will file a ticket upstream for this.

**Comment by kyledecot** [comment]
Thanks everyone!
