### ISSUE TITLE
Documentation for alias is incorrect, cannot take String

### ISSUE THREAD

**Issue by dblock** [documenting-ruby/ruby#23]
http://ruby-doc.org/docs/keywords/1.9 incorrectly states that arguments to `alias` can be `String`. See https://github.com/bbatsov/rubocop/pull/657. I spent a long time trying to figure out whether
- This is still an issue in the current documentation. I cannot for the life of me find the doc for `alias` in the current tree.
- How to fix this for 1.9.x.

Help?

**Comment by zzak** [comment]
Thanks for the report, I wasn't able to find this file in the current documentation.

Can you send me a link? Unfortunately we don't maintain ruby-doc.org, so I don't have access to their files.

After testing, you can't pass a string to `alias`, only a symbol or local variable name (can be undefined)

``` ruby
def foo
  "zomg"
end

alias "bar" foo #=> SyntaxError: (irb):10: syntax error, unexpected tSTRING_BEG

alias :bar foo
bar #=> "zomg"
# notice it creates a local variable named bar (used without the symbol syntax)

alias undefined foo
undefined #=> "zomg"
```

**Comment by dblock** [comment]
@zzak Can you find where `alias` _is_ documented in the current documentation? I couldn't.

**Comment by zzak** [comment]
@dblock `alias` isn't documented because its a keyword.

I started working on a `./doc/keywords.rdoc` file which lists an (maybe) explains each keyword, but haven't had time to finish it.

If you're interested I can open a work in progress pull request and you can fork my branch if you'd like to help?

**Comment by dblock** [comment]
Def. open an issue and cc: me on it. Making no promises, but seems like it's something needed so me or someone will pick it up.

**Comment by zzak** [comment]
Giving this a close since there has been no further update.

Anyone is welcome to improve the docs for keywords.
