### ISSUE TITLE
Documenting aliases

### ISSUE THREAD

**Issue by ggarnier** [documenting-ruby/ruby#24]
When I search for some method on ruby-doc, I miss an information about aliases for a method, like on _Enumerable_ module: _select_ is an alias to _find_all_, but I can't know that when I read the documentation (except when I click "toggle source" and realize that both show the same code).
Is there a solution to show that information (other than adding on _find_all_ doc something like "select" and "find_all" are aliases)?

**Comment by zzak** [comment]
Unfortunately we don't maintain ruby-doc.org

However, RDoc with the darkfish generator (used by default to generate HTML from RDoc) does support displaying aliased methods together.

I'm not sure there's anything we can do on our end, but if you have any ideas I'd love to hear them. You're welcome to open a ticket, comment here, or submit a patch anytime.

Thanks!

**Comment by ggarnier** [comment]
I just realized that `collect_concat` method on [Enumerable documentation](http://www.ruby-doc.org/core-2.0.0/Enumerable.html#method-i-collect_concat) shows a note saying it's an alias for `flat_map`. Maybe that format could be used to document other aliases.
