### ISSUE TITLE
Documentation for the 'shell' library

### ISSUE THREAD

**Issue by reprah** [documenting-ruby/ruby#26]
Hi, I  wanted to see if I could help fill in the docs for [shell](http://ruby-doc.org/stdlib-2.1.0/libdoc/shell/rdoc/index.html). A lot of the classes in that namespace don't have descriptions for their methods yet.

Has someone else prioritized this or can I go ahead?

Also I'd like to know where you would prefer people to offer documentation when they do... In this repo? In the main Ruby repo on github? I've seen people do both. Thanks!!

**Comment by zzak** [comment]
@reprah Sounds good!

You can send patches where ever you would like. If this is more convenient or comfortable for you, it works for me!

Let me know if you’d like a review at any time.

**Comment by zzak** [comment]
Closing in favor of ruby/ruby#516
