### ISSUE TITLE
Documenting global variables (particularly IO instances)

### ISSUE THREAD

**Issue by siruguri** [documenting-ruby/ruby#27]
I was trying to explain puts to someone, and noticed that the documentation says that `puts` is "[equivalent to $stdout.puts](http://ruby-doc.org/core-2.1.0/Kernel.html#method-i-puts)" That led me to try and track down where to explain what `$stdout` refers to but I couldn't find any obvious place to add it in... I'd imagine it'd have to be somewhere in a list of "default Ruby global variables," but it isn't clear to me where that should be.

Should the [documentation for IO](http://www.ruby-doc.org/core-2.1.0/IO.html) be the place to list at least global variables of that class?

**Comment by zzak** [comment]
We have `./doc/globals.rdoc` which includes a list of all the global variables in Ruby.

**Comment by siruguri** [comment]
Thanks - that's helpful!
