### ISSUE TITLE
example for find shows detect instead of find

### ISSUE THREAD

**Issue by JessRudder** [documenting-ruby/ruby#35]
The documented example for find uses detect instead of find.

**Comment by zzak** [comment]
@JessRudder Thanks for the report!

I thought this was recently fixed, or something, but maybe not.

Do you know where you saw the examples?

**Comment by vipulnsward** [comment]
This was fixed in https://github.com/documenting-ruby/ruby/pull/34

**Comment by zzak** [comment]
@vipulnsward ahh, thanks for reminding me!
