### ISSUE TITLE
Working on DEBUGGER__ Class

### ISSUE THREAD

**Issue by tomkadwill** [documenting-ruby/ruby#38]
Was great to meet @zzak at BrightonRuby Conf, thanks for the inspiration to start working on documenting Ruby.

I've run rdoc for a list of undocumented areas and I've picked the `DEBUGGER__` Class. If there are any reasons why `DEBUGGER__` is a bad choice please let me know. Otherwise a PR should follow soon :)

**Comment by zzak** [comment]
@tomkadwill Awesome! Yeah I think the `DEBUGGER__` class is well documented, but many methods are missing docs. Just be aware that we might not want to document every method in this class, only methods used by actual humans.

**Comment by zzak** [comment]
@tomkadwill, if you have any questions please don't hesitate. I'm giving this ticket a close since there has been no recent update.

Thanks
