### ISSUE TITLE
Symbol public instance method == duplicated in docs

### ISSUE THREAD

**Issue by craftninja** [documenting-ruby/ruby#40]
Hi!

I noticed that the Symbol Public Instance Method == was duplicated in the ruby-docs site. I checked the string.c file in the documenting-ruby/ruby repo, but it does not seem duplicated there. Perhaps an issue occurs in the generation of the documentation? Attached is a screenshot.

Let me know if I can do anything!

Kindly,
Emily

---

![screen shot 2014-07-31 at 9 57 25 am](https://cloud.githubusercontent.com/assets/6353499/3767266/d01e6140-18cb-11e4-9cf5-e672805ff7d5.png)

**Comment by zzak** [comment]
This is a bug in the rdoc generator, and not likely due to anything with the documentation itself.

Thanks for reporting! Giving this a close.
