### ISSUE TITLE
Documenting Array.reject to mention that it maintains the order of the elements it does not reject

### ISSUE THREAD

**Issue by NebuPookins** [documenting-ruby/ruby#41]

**Comment by zzak** [comment]
Hello @NebuPookins!

While I agree this may not be intentionally obvious, it's important to note that all Arrays in ruby are ordered. So we should expect that any destructive methods also maintain that order, without expressly stating that behavior. In fact, the very first sentence of the description of the Array constant is as follows:

> Arrays are ordered, integer-indexed collections of any object.

If that makes sense to you, I'd like to close this ticket and the pull request in hopes we can find a better way to express this behavior without explaining it for every method.

**Comment by NebuPookins** [comment]
Hi @zzak 
1. Do you think that the probability that we'll find a good way of expressing this behavior will increase if this ticket is closed vs if it remains open?
2. The original documentation says "Returns a **new** array containing the items in +self+ for which the given block is not +true+." (emphasis added) implying that this is not a destructive update at all, but instead leaves the original array untouched and generates a new array. Are you assuming that there is some sort of relationship between the ordering of elements of the newly generated array and the ordering of the elements of the original array? Why make that assumption if there's nothing in the documentation of the original method that even implies such a relationship might exist?

**Comment by zzak** [comment]
I'm not assuming there is any relationship between them.

I guess the order of the original array is maintained because the Array is copied.

**Comment by NebuPookins** [comment]
So you're saying that the ordering of the elements in the resulting array is an incidental quirk of how the method is currently implemented, but that the ordering may be different in the future if we find a more efficient way to implement it?

**Comment by NebuPookins** [comment]
What do you recommend as the appropriate steps to get this issue fixed? It doesn't seem like commenting on this github issue is getting anywhere, for example.
