### ISSUE TITLE
Add version switcher to docs site?

### ISSUE THREAD

**Issue by nathanl** [documenting-ruby/ruby#45]
I just searched the web for "ruby StringIO" and landed on the [1.9.3 documentation](http://ruby-doc.org/stdlib-1.9.3/libdoc/stringio/rdoc/StringIO.html). I wanted to see the StringIO docs for a version >= 2.0. There is currently no easy way to get from one to the other, and no way to predict which version a search engine will find first.

Could we add a dropdown on each doc page, linking to the corresponding page for other versions of Ruby? If there are too many, maybe it could be limited to the most recent N releases, or the the most recent N on each branch.

**Comment by zzak** [comment]
We actually don't maintain that website.. but the last time I checked James Britt was the owner of the site.

As a side note, we are somewhat working on building official docs site at docs.ruby-lang.org, but it's not yet finished. Stay tuned!

**Comment by zzak** [comment]
Paging @jamesbritt, maybe this will help you!
