### ISSUE TITLE
IO.Select use on OpenSSL::SSL::SSLSocket

### ISSUE THREAD

**Issue by h-m-m** [documenting-ruby/ruby#48]
I've been looking for ways to make some of the existing documentation easier to read. Looking through [io.c](https://github.com/documenting-ruby/ruby/blob/trunk/io.c#L8743), I noticed the comment for IO.select currently says

> Especially, the combination of nonblocking methods and
> <code>IO.select</code> is preferred for <code>IO</code> like
> objects such as <code>OpenSSL::SSL::SSLSocket</code>.

It then goes on to explain several reasons why that could be a bad idea. Is it really preferred as long as you account for those potential problems, or did someone leave out a word when writing this documentation?

**Comment by zzak** [comment]
@h-m-m To (try to) answer your question, no. I don't think it's a bad idea: if only you're aware of these potential problems. Those "warnings" only exist to give developers an idea of what to expect when using this API.

That said, the wording here is kind of weird and would welcome a patch to improve it.

If you have any other questions, please don't hesitate. I'm only closing this ticket as there is no other immediate actions required here.
