### ISSUE TITLE
Attempting to document Float

### ISSUE THREAD

**Issue by ZachBeta** [documenting-ruby/ruby#5]

**Comment by zzak** [comment]
@ZachBeta Did you attach a patch?

**Comment by ZachBeta** [comment]
Just pushed the commit to my fork.

Going to revisit this in the AM.

**Comment by zzak** [comment]
Awesome, looks like ZachBeta/ruby@e4a47c9 I will review it and let you know, thanks for the patch!

**Comment by ZachBeta** [comment]
B-)

**Comment by zzak** [comment]
@ZachBeta and @orenyk This patch landed in [r39369](https://github.com/ruby/ruby/commit/8d4a11c), thanks so much for your contribution!

**Comment by ZachBeta** [comment]
![](http://www.captionite.com/templates/success_kid.jpg)
