### ISSUE TITLE
Hash: JavaScript-like colon notation allowed for Symbol keys, even when other key in the same Hash aren't Symbols

### ISSUE THREAD

**Issue by das-g** [documenting-ruby/ruby#50]
On http://ruby-doc.org/core-2.2.2/Hash.html#method-i-store, the notation `{ my_key: 5 }` (available since Ruby 1.9) is introduced with

> Hashes allow an alternate syntax form when your keys are **always** symbols.

(Emphasis mine.)

This suggests that this syntax will **only** be allowed for literals of Hashes where **all** keys are are Symbols. However, experiments show it works fine for Hashes of mixed key types:

```
{"a string" => 1, a_symbol: 2, Math::PI => 3 }
```

 (Of course, the colon syntax can only be used for those keys that _are_ Symbols.)

**Comment by das-g** [comment]
I suggest to change that to

> Hashes allow an alternate syntax form for keys that are symbols:

**Comment by zzak** [comment]
@das-g Thank you for your patch!

This was committed in r51506.
