### ISSUE TITLE
Found some spell error

### ISSUE THREAD

**Issue by Matrixbirds** [documenting-ruby/ruby#54]
[![image](https://cloud.githubusercontent.com/assets/9990676/10391918/dfa00fe8-6eb4-11e5-8e7f-21f040278ebe.png)](http://ruby-doc.org/core-2.2.2/_lib/racc/rdoc/grammar_en_rdoc.html#label-Class+Block)

[http://ruby-doc.org/core-2.2.2/_lib/racc/rdoc/grammar_en_rdoc.html#label-Class+Block](http://ruby-doc.org/core-2.2.2/_lib/racc/rdoc/grammar_en_rdoc.html#label-Class+Block)

**Comment by davydovanton** [comment]
@Matrixbirds hello, I check 2.3.0 documentation and I can see that this typos was fixed. Thanks for helping! :heart: 

![screenshot 2016-03-17 03 35 31](https://cloud.githubusercontent.com/assets/1147484/13832894/d5edf09c-ebf9-11e5-82da-fcdc3ebfa346.jpg)
