### ISSUE TITLE
Specifying Logger.new shift_age option default

### ISSUE THREAD

**Issue by spacemunkay** [documenting-ruby/ruby#64]
http://ruby-doc.org/stdlib-2.3.0/libdoc/logger/rdoc/Logger.html#new-method

From only looking at the docs, it's not obvious what the default value is for shift_age, nor what value disables the option.  The only way to find out is to look at the code itself.

Can submit a PR with the following adjustment: https://github.com/documenting-ruby/ruby/compare/trunk...spacemunkay:specify-logger-shift-age-default

**Comment by davydovanton** [comment]
hello @spacemunkay, nice catch! :+1:
I think PR will be great.

**Comment by spacemunkay** [comment]
@davydovanton No problem!

**Comment by spacemunkay** [comment]
Issue solved with changeset https://bugs.ruby-lang.org/projects/ruby-trunk/repository/revisions/56420
