### ISSUE TITLE
mark this project as dead

### ISSUE THREAD

**Issue by matkoniecz** [documenting-ruby/ruby#67]
http://documenting-ruby.org/step-by-step-guide.html is quite prominent result for googling about ruby documentation.

It would be useful to describe it as dead on its landing page give activity here ([no response to PR since 2014](https://github.com/documenting-ruby/ruby/pull/36#issuecomment-50470728) etc).

**Comment by zzak** [comment]
Hey, I'm sorry.

Much of these contributions could see more attention if submitted upstream but the submitter may feel more comfortable submitting to a fork. That was (I believe) the original intention of this project.

If you'd like to ensure this project lives on, there may be a way to save it.

Any patches which don't require feedback from the submitter could be reported upstream, either to Ruby's [bug tracker](https://bugs.ruby-lang.org/) or submitted as a pull request to the [git mirror](https://github.com/ruby/ruby).

This was actually one of my first jobs as a contributor to Ruby, and still a valuable to the project.

I don't think we should "mark dead", although not as active as I'd like, some people may still find it useful if they're not comfortable contributing to Ruby outlets directly.

**Comment by danbernier** [comment]
Thanks for bringing this up, @matkoniecz, I'd forgotten all about that PR! :tada:
